/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsNewRouteImport } from './routes/tools.new'
import { Route as FinanceDreRouteImport } from './routes/finance.dre'
import { Route as FinanceDashboardRouteImport } from './routes/finance.dashboard'
import { Route as FinanceCashFlowRouteImport } from './routes/finance.cash-flow'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardUnitsRouteImport } from './routes/dashboard.units'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminCompanyRouteImport } from './routes/admin.company'
import { Route as ToolsTransfersIndexRouteImport } from './routes/tools.transfers.index'
import { Route as ToolsMaintenancesIndexRouteImport } from './routes/tools.maintenances.index'
import { Route as ToolsIdIndexRouteImport } from './routes/tools.$id.index'
import { Route as OperationsWorkOrdersIndexRouteImport } from './routes/operations.work-orders.index'
import { Route as OperationsQuotesIndexRouteImport } from './routes/operations.quotes.index'
import { Route as OperationsInspectionsIndexRouteImport } from './routes/operations.inspections.index'
import { Route as InventoryTransfersIndexRouteImport } from './routes/inventory.transfers.index'
import { Route as InventoryStocksIndexRouteImport } from './routes/inventory.stocks.index'
import { Route as InventoryProductsIndexRouteImport } from './routes/inventory.products.index'
import { Route as InventoryMovementsIndexRouteImport } from './routes/inventory.movements.index'
import { Route as FinanceTransactionsIndexRouteImport } from './routes/finance.transactions.index'
import { Route as FinanceReceivablesIndexRouteImport } from './routes/finance.receivables.index'
import { Route as FinancePayablesIndexRouteImport } from './routes/finance.payables.index'
import { Route as FinanceAccountsIndexRouteImport } from './routes/finance.accounts.index'
import { Route as CrmVehiclesIndexRouteImport } from './routes/crm.vehicles.index'
import { Route as CrmCustomersIndexRouteImport } from './routes/crm.customers.index'
import { Route as ToolsIdEditRouteImport } from './routes/tools.$id.edit'
import { Route as PortalQuotesIdRouteImport } from './routes/portal.quotes.$id'
import { Route as OperationsWorkOrdersKanbanRouteImport } from './routes/operations.work-orders.kanban'
import { Route as OperationsWorkOrdersIdRouteImport } from './routes/operations.work-orders.$id'
import { Route as OperationsSchedulingNewRouteImport } from './routes/operations.scheduling.new'
import { Route as OperationsSchedulingCheckinRouteImport } from './routes/operations.scheduling.checkin'
import { Route as OperationsSchedulingCalendarRouteImport } from './routes/operations.scheduling.calendar'
import { Route as OperationsQuotesNewRouteImport } from './routes/operations.quotes.new'
import { Route as OperationsQuotesIdRouteImport } from './routes/operations.quotes.$id'
import { Route as OperationsInspectionsNewRouteImport } from './routes/operations.inspections.new'
import { Route as OperationsInspectionsIdRouteImport } from './routes/operations.inspections.$id'
import { Route as InventoryProductsNewRouteImport } from './routes/inventory.products.new'
import { Route as InventoryProductsIdRouteImport } from './routes/inventory.products.$id'
import { Route as CrmVehiclesNewRouteImport } from './routes/crm.vehicles.new'
import { Route as CrmVehiclesIdRouteImport } from './routes/crm.vehicles.$id'
import { Route as CrmCustomersNewRouteImport } from './routes/crm.customers.new'
import { Route as CrmCustomersIdRouteImport } from './routes/crm.customers.$id'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth.callback.google'
import { Route as PortalVehiclesIdHistoryRouteImport } from './routes/portal.vehicles.$id.history'
import { Route as OperationsVehiclesIdHistoryRouteImport } from './routes/operations.vehicles.$id.history'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNewRoute = ToolsNewRouteImport.update({
  id: '/tools/new',
  path: '/tools/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDreRoute = FinanceDreRouteImport.update({
  id: '/finance/dre',
  path: '/finance/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance/dashboard',
  path: '/finance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCashFlowRoute = FinanceCashFlowRouteImport.update({
  id: '/finance/cash-flow',
  path: '/finance/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnitsRoute = DashboardUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompanyRoute = AdminCompanyRouteImport.update({
  id: '/admin/company',
  path: '/admin/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTransfersIndexRoute = ToolsTransfersIndexRouteImport.update({
  id: '/tools/transfers/',
  path: '/tools/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMaintenancesIndexRoute = ToolsMaintenancesIndexRouteImport.update({
  id: '/tools/maintenances/',
  path: '/tools/maintenances/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIdIndexRoute = ToolsIdIndexRouteImport.update({
  id: '/tools/$id/',
  path: '/tools/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsWorkOrdersIndexRoute =
  OperationsWorkOrdersIndexRouteImport.update({
    id: '/operations/work-orders/',
    path: '/operations/work-orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperationsQuotesIndexRoute = OperationsQuotesIndexRouteImport.update({
  id: '/operations/quotes/',
  path: '/operations/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsInspectionsIndexRoute =
  OperationsInspectionsIndexRouteImport.update({
    id: '/operations/inspections/',
    path: '/operations/inspections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryTransfersIndexRoute = InventoryTransfersIndexRouteImport.update({
  id: '/inventory/transfers/',
  path: '/inventory/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStocksIndexRoute = InventoryStocksIndexRouteImport.update({
  id: '/inventory/stocks/',
  path: '/inventory/stocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsIndexRoute = InventoryProductsIndexRouteImport.update({
  id: '/inventory/products/',
  path: '/inventory/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryMovementsIndexRoute = InventoryMovementsIndexRouteImport.update({
  id: '/inventory/movements/',
  path: '/inventory/movements/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTransactionsIndexRoute =
  FinanceTransactionsIndexRouteImport.update({
    id: '/finance/transactions/',
    path: '/finance/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceReceivablesIndexRoute = FinanceReceivablesIndexRouteImport.update({
  id: '/finance/receivables/',
  path: '/finance/receivables/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePayablesIndexRoute = FinancePayablesIndexRouteImport.update({
  id: '/finance/payables/',
  path: '/finance/payables/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountsIndexRoute = FinanceAccountsIndexRouteImport.update({
  id: '/finance/accounts/',
  path: '/finance/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmVehiclesIndexRoute = CrmVehiclesIndexRouteImport.update({
  id: '/crm/vehicles/',
  path: '/crm/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersIndexRoute = CrmCustomersIndexRouteImport.update({
  id: '/crm/customers/',
  path: '/crm/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIdEditRoute = ToolsIdEditRouteImport.update({
  id: '/tools/$id/edit',
  path: '/tools/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalQuotesIdRoute = PortalQuotesIdRouteImport.update({
  id: '/portal/quotes/$id',
  path: '/portal/quotes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsWorkOrdersKanbanRoute =
  OperationsWorkOrdersKanbanRouteImport.update({
    id: '/operations/work-orders/kanban',
    path: '/operations/work-orders/kanban',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperationsWorkOrdersIdRoute = OperationsWorkOrdersIdRouteImport.update({
  id: '/operations/work-orders/$id',
  path: '/operations/work-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsSchedulingNewRoute = OperationsSchedulingNewRouteImport.update({
  id: '/operations/scheduling/new',
  path: '/operations/scheduling/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsSchedulingCheckinRoute =
  OperationsSchedulingCheckinRouteImport.update({
    id: '/operations/scheduling/checkin',
    path: '/operations/scheduling/checkin',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperationsSchedulingCalendarRoute =
  OperationsSchedulingCalendarRouteImport.update({
    id: '/operations/scheduling/calendar',
    path: '/operations/scheduling/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperationsQuotesNewRoute = OperationsQuotesNewRouteImport.update({
  id: '/operations/quotes/new',
  path: '/operations/quotes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsQuotesIdRoute = OperationsQuotesIdRouteImport.update({
  id: '/operations/quotes/$id',
  path: '/operations/quotes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsInspectionsNewRoute =
  OperationsInspectionsNewRouteImport.update({
    id: '/operations/inspections/new',
    path: '/operations/inspections/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperationsInspectionsIdRoute = OperationsInspectionsIdRouteImport.update({
  id: '/operations/inspections/$id',
  path: '/operations/inspections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsNewRoute = InventoryProductsNewRouteImport.update({
  id: '/inventory/products/new',
  path: '/inventory/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsIdRoute = InventoryProductsIdRouteImport.update({
  id: '/inventory/products/$id',
  path: '/inventory/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmVehiclesNewRoute = CrmVehiclesNewRouteImport.update({
  id: '/crm/vehicles/new',
  path: '/crm/vehicles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmVehiclesIdRoute = CrmVehiclesIdRouteImport.update({
  id: '/crm/vehicles/$id',
  path: '/crm/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersNewRoute = CrmCustomersNewRouteImport.update({
  id: '/crm/customers/new',
  path: '/crm/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersIdRoute = CrmCustomersIdRouteImport.update({
  id: '/crm/customers/$id',
  path: '/crm/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalVehiclesIdHistoryRoute = PortalVehiclesIdHistoryRouteImport.update({
  id: '/portal/vehicles/$id/history',
  path: '/portal/vehicles/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsVehiclesIdHistoryRoute =
  OperationsVehiclesIdHistoryRouteImport.update({
    id: '/operations/vehicles/$id/history',
    path: '/operations/vehicles/$id/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/dre': typeof FinanceDreRoute
  '/tools/new': typeof ToolsNewRoute
  '/tools/': typeof ToolsIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
  '/crm/customers/new': typeof CrmCustomersNewRoute
  '/crm/vehicles/$id': typeof CrmVehiclesIdRoute
  '/crm/vehicles/new': typeof CrmVehiclesNewRoute
  '/inventory/products/$id': typeof InventoryProductsIdRoute
  '/inventory/products/new': typeof InventoryProductsNewRoute
  '/operations/inspections/$id': typeof OperationsInspectionsIdRoute
  '/operations/inspections/new': typeof OperationsInspectionsNewRoute
  '/operations/quotes/$id': typeof OperationsQuotesIdRoute
  '/operations/quotes/new': typeof OperationsQuotesNewRoute
  '/operations/scheduling/calendar': typeof OperationsSchedulingCalendarRoute
  '/operations/scheduling/checkin': typeof OperationsSchedulingCheckinRoute
  '/operations/scheduling/new': typeof OperationsSchedulingNewRoute
  '/operations/work-orders/$id': typeof OperationsWorkOrdersIdRoute
  '/operations/work-orders/kanban': typeof OperationsWorkOrdersKanbanRoute
  '/portal/quotes/$id': typeof PortalQuotesIdRoute
  '/tools/$id/edit': typeof ToolsIdEditRoute
  '/crm/customers/': typeof CrmCustomersIndexRoute
  '/crm/vehicles/': typeof CrmVehiclesIndexRoute
  '/finance/accounts/': typeof FinanceAccountsIndexRoute
  '/finance/payables/': typeof FinancePayablesIndexRoute
  '/finance/receivables/': typeof FinanceReceivablesIndexRoute
  '/finance/transactions/': typeof FinanceTransactionsIndexRoute
  '/inventory/movements/': typeof InventoryMovementsIndexRoute
  '/inventory/products/': typeof InventoryProductsIndexRoute
  '/inventory/stocks/': typeof InventoryStocksIndexRoute
  '/inventory/transfers/': typeof InventoryTransfersIndexRoute
  '/operations/inspections/': typeof OperationsInspectionsIndexRoute
  '/operations/quotes/': typeof OperationsQuotesIndexRoute
  '/operations/work-orders/': typeof OperationsWorkOrdersIndexRoute
  '/tools/$id/': typeof ToolsIdIndexRoute
  '/tools/maintenances/': typeof ToolsMaintenancesIndexRoute
  '/tools/transfers/': typeof ToolsTransfersIndexRoute
  '/operations/vehicles/$id/history': typeof OperationsVehiclesIdHistoryRoute
  '/portal/vehicles/$id/history': typeof PortalVehiclesIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/dre': typeof FinanceDreRoute
  '/tools/new': typeof ToolsNewRoute
  '/tools': typeof ToolsIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
  '/crm/customers/new': typeof CrmCustomersNewRoute
  '/crm/vehicles/$id': typeof CrmVehiclesIdRoute
  '/crm/vehicles/new': typeof CrmVehiclesNewRoute
  '/inventory/products/$id': typeof InventoryProductsIdRoute
  '/inventory/products/new': typeof InventoryProductsNewRoute
  '/operations/inspections/$id': typeof OperationsInspectionsIdRoute
  '/operations/inspections/new': typeof OperationsInspectionsNewRoute
  '/operations/quotes/$id': typeof OperationsQuotesIdRoute
  '/operations/quotes/new': typeof OperationsQuotesNewRoute
  '/operations/scheduling/calendar': typeof OperationsSchedulingCalendarRoute
  '/operations/scheduling/checkin': typeof OperationsSchedulingCheckinRoute
  '/operations/scheduling/new': typeof OperationsSchedulingNewRoute
  '/operations/work-orders/$id': typeof OperationsWorkOrdersIdRoute
  '/operations/work-orders/kanban': typeof OperationsWorkOrdersKanbanRoute
  '/portal/quotes/$id': typeof PortalQuotesIdRoute
  '/tools/$id/edit': typeof ToolsIdEditRoute
  '/crm/customers': typeof CrmCustomersIndexRoute
  '/crm/vehicles': typeof CrmVehiclesIndexRoute
  '/finance/accounts': typeof FinanceAccountsIndexRoute
  '/finance/payables': typeof FinancePayablesIndexRoute
  '/finance/receivables': typeof FinanceReceivablesIndexRoute
  '/finance/transactions': typeof FinanceTransactionsIndexRoute
  '/inventory/movements': typeof InventoryMovementsIndexRoute
  '/inventory/products': typeof InventoryProductsIndexRoute
  '/inventory/stocks': typeof InventoryStocksIndexRoute
  '/inventory/transfers': typeof InventoryTransfersIndexRoute
  '/operations/inspections': typeof OperationsInspectionsIndexRoute
  '/operations/quotes': typeof OperationsQuotesIndexRoute
  '/operations/work-orders': typeof OperationsWorkOrdersIndexRoute
  '/tools/$id': typeof ToolsIdIndexRoute
  '/tools/maintenances': typeof ToolsMaintenancesIndexRoute
  '/tools/transfers': typeof ToolsTransfersIndexRoute
  '/operations/vehicles/$id/history': typeof OperationsVehiclesIdHistoryRoute
  '/portal/vehicles/$id/history': typeof PortalVehiclesIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/dre': typeof FinanceDreRoute
  '/tools/new': typeof ToolsNewRoute
  '/tools/': typeof ToolsIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
  '/crm/customers/new': typeof CrmCustomersNewRoute
  '/crm/vehicles/$id': typeof CrmVehiclesIdRoute
  '/crm/vehicles/new': typeof CrmVehiclesNewRoute
  '/inventory/products/$id': typeof InventoryProductsIdRoute
  '/inventory/products/new': typeof InventoryProductsNewRoute
  '/operations/inspections/$id': typeof OperationsInspectionsIdRoute
  '/operations/inspections/new': typeof OperationsInspectionsNewRoute
  '/operations/quotes/$id': typeof OperationsQuotesIdRoute
  '/operations/quotes/new': typeof OperationsQuotesNewRoute
  '/operations/scheduling/calendar': typeof OperationsSchedulingCalendarRoute
  '/operations/scheduling/checkin': typeof OperationsSchedulingCheckinRoute
  '/operations/scheduling/new': typeof OperationsSchedulingNewRoute
  '/operations/work-orders/$id': typeof OperationsWorkOrdersIdRoute
  '/operations/work-orders/kanban': typeof OperationsWorkOrdersKanbanRoute
  '/portal/quotes/$id': typeof PortalQuotesIdRoute
  '/tools/$id/edit': typeof ToolsIdEditRoute
  '/crm/customers/': typeof CrmCustomersIndexRoute
  '/crm/vehicles/': typeof CrmVehiclesIndexRoute
  '/finance/accounts/': typeof FinanceAccountsIndexRoute
  '/finance/payables/': typeof FinancePayablesIndexRoute
  '/finance/receivables/': typeof FinanceReceivablesIndexRoute
  '/finance/transactions/': typeof FinanceTransactionsIndexRoute
  '/inventory/movements/': typeof InventoryMovementsIndexRoute
  '/inventory/products/': typeof InventoryProductsIndexRoute
  '/inventory/stocks/': typeof InventoryStocksIndexRoute
  '/inventory/transfers/': typeof InventoryTransfersIndexRoute
  '/operations/inspections/': typeof OperationsInspectionsIndexRoute
  '/operations/quotes/': typeof OperationsQuotesIndexRoute
  '/operations/work-orders/': typeof OperationsWorkOrdersIndexRoute
  '/tools/$id/': typeof ToolsIdIndexRoute
  '/tools/maintenances/': typeof ToolsMaintenancesIndexRoute
  '/tools/transfers/': typeof ToolsTransfersIndexRoute
  '/operations/vehicles/$id/history': typeof OperationsVehiclesIdHistoryRoute
  '/portal/vehicles/$id/history': typeof PortalVehiclesIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/company'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/dre'
    | '/tools/new'
    | '/tools/'
    | '/auth/callback/google'
    | '/crm/customers/$id'
    | '/crm/customers/new'
    | '/crm/vehicles/$id'
    | '/crm/vehicles/new'
    | '/inventory/products/$id'
    | '/inventory/products/new'
    | '/operations/inspections/$id'
    | '/operations/inspections/new'
    | '/operations/quotes/$id'
    | '/operations/quotes/new'
    | '/operations/scheduling/calendar'
    | '/operations/scheduling/checkin'
    | '/operations/scheduling/new'
    | '/operations/work-orders/$id'
    | '/operations/work-orders/kanban'
    | '/portal/quotes/$id'
    | '/tools/$id/edit'
    | '/crm/customers/'
    | '/crm/vehicles/'
    | '/finance/accounts/'
    | '/finance/payables/'
    | '/finance/receivables/'
    | '/finance/transactions/'
    | '/inventory/movements/'
    | '/inventory/products/'
    | '/inventory/stocks/'
    | '/inventory/transfers/'
    | '/operations/inspections/'
    | '/operations/quotes/'
    | '/operations/work-orders/'
    | '/tools/$id/'
    | '/tools/maintenances/'
    | '/tools/transfers/'
    | '/operations/vehicles/$id/history'
    | '/portal/vehicles/$id/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/company'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/dre'
    | '/tools/new'
    | '/tools'
    | '/auth/callback/google'
    | '/crm/customers/$id'
    | '/crm/customers/new'
    | '/crm/vehicles/$id'
    | '/crm/vehicles/new'
    | '/inventory/products/$id'
    | '/inventory/products/new'
    | '/operations/inspections/$id'
    | '/operations/inspections/new'
    | '/operations/quotes/$id'
    | '/operations/quotes/new'
    | '/operations/scheduling/calendar'
    | '/operations/scheduling/checkin'
    | '/operations/scheduling/new'
    | '/operations/work-orders/$id'
    | '/operations/work-orders/kanban'
    | '/portal/quotes/$id'
    | '/tools/$id/edit'
    | '/crm/customers'
    | '/crm/vehicles'
    | '/finance/accounts'
    | '/finance/payables'
    | '/finance/receivables'
    | '/finance/transactions'
    | '/inventory/movements'
    | '/inventory/products'
    | '/inventory/stocks'
    | '/inventory/transfers'
    | '/operations/inspections'
    | '/operations/quotes'
    | '/operations/work-orders'
    | '/tools/$id'
    | '/tools/maintenances'
    | '/tools/transfers'
    | '/operations/vehicles/$id/history'
    | '/portal/vehicles/$id/history'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/company'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/dre'
    | '/tools/new'
    | '/tools/'
    | '/auth/callback/google'
    | '/crm/customers/$id'
    | '/crm/customers/new'
    | '/crm/vehicles/$id'
    | '/crm/vehicles/new'
    | '/inventory/products/$id'
    | '/inventory/products/new'
    | '/operations/inspections/$id'
    | '/operations/inspections/new'
    | '/operations/quotes/$id'
    | '/operations/quotes/new'
    | '/operations/scheduling/calendar'
    | '/operations/scheduling/checkin'
    | '/operations/scheduling/new'
    | '/operations/work-orders/$id'
    | '/operations/work-orders/kanban'
    | '/portal/quotes/$id'
    | '/tools/$id/edit'
    | '/crm/customers/'
    | '/crm/vehicles/'
    | '/finance/accounts/'
    | '/finance/payables/'
    | '/finance/receivables/'
    | '/finance/transactions/'
    | '/inventory/movements/'
    | '/inventory/products/'
    | '/inventory/stocks/'
    | '/inventory/transfers/'
    | '/operations/inspections/'
    | '/operations/quotes/'
    | '/operations/work-orders/'
    | '/tools/$id/'
    | '/tools/maintenances/'
    | '/tools/transfers/'
    | '/operations/vehicles/$id/history'
    | '/portal/vehicles/$id/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminCompanyRoute: typeof AdminCompanyRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  FinanceCashFlowRoute: typeof FinanceCashFlowRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  FinanceDreRoute: typeof FinanceDreRoute
  ToolsNewRoute: typeof ToolsNewRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
  CrmCustomersIdRoute: typeof CrmCustomersIdRoute
  CrmCustomersNewRoute: typeof CrmCustomersNewRoute
  CrmVehiclesIdRoute: typeof CrmVehiclesIdRoute
  CrmVehiclesNewRoute: typeof CrmVehiclesNewRoute
  InventoryProductsIdRoute: typeof InventoryProductsIdRoute
  InventoryProductsNewRoute: typeof InventoryProductsNewRoute
  OperationsInspectionsIdRoute: typeof OperationsInspectionsIdRoute
  OperationsInspectionsNewRoute: typeof OperationsInspectionsNewRoute
  OperationsQuotesIdRoute: typeof OperationsQuotesIdRoute
  OperationsQuotesNewRoute: typeof OperationsQuotesNewRoute
  OperationsSchedulingCalendarRoute: typeof OperationsSchedulingCalendarRoute
  OperationsSchedulingCheckinRoute: typeof OperationsSchedulingCheckinRoute
  OperationsSchedulingNewRoute: typeof OperationsSchedulingNewRoute
  OperationsWorkOrdersIdRoute: typeof OperationsWorkOrdersIdRoute
  OperationsWorkOrdersKanbanRoute: typeof OperationsWorkOrdersKanbanRoute
  PortalQuotesIdRoute: typeof PortalQuotesIdRoute
  ToolsIdEditRoute: typeof ToolsIdEditRoute
  CrmCustomersIndexRoute: typeof CrmCustomersIndexRoute
  CrmVehiclesIndexRoute: typeof CrmVehiclesIndexRoute
  FinanceAccountsIndexRoute: typeof FinanceAccountsIndexRoute
  FinancePayablesIndexRoute: typeof FinancePayablesIndexRoute
  FinanceReceivablesIndexRoute: typeof FinanceReceivablesIndexRoute
  FinanceTransactionsIndexRoute: typeof FinanceTransactionsIndexRoute
  InventoryMovementsIndexRoute: typeof InventoryMovementsIndexRoute
  InventoryProductsIndexRoute: typeof InventoryProductsIndexRoute
  InventoryStocksIndexRoute: typeof InventoryStocksIndexRoute
  InventoryTransfersIndexRoute: typeof InventoryTransfersIndexRoute
  OperationsInspectionsIndexRoute: typeof OperationsInspectionsIndexRoute
  OperationsQuotesIndexRoute: typeof OperationsQuotesIndexRoute
  OperationsWorkOrdersIndexRoute: typeof OperationsWorkOrdersIndexRoute
  ToolsIdIndexRoute: typeof ToolsIdIndexRoute
  ToolsMaintenancesIndexRoute: typeof ToolsMaintenancesIndexRoute
  ToolsTransfersIndexRoute: typeof ToolsTransfersIndexRoute
  OperationsVehiclesIdHistoryRoute: typeof OperationsVehiclesIdHistoryRoute
  PortalVehiclesIdHistoryRoute: typeof PortalVehiclesIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/new': {
      id: '/tools/new'
      path: '/tools/new'
      fullPath: '/tools/new'
      preLoaderRoute: typeof ToolsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/dre': {
      id: '/finance/dre'
      path: '/finance/dre'
      fullPath: '/finance/dre'
      preLoaderRoute: typeof FinanceDreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/finance/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/cash-flow': {
      id: '/finance/cash-flow'
      path: '/finance/cash-flow'
      fullPath: '/finance/cash-flow'
      preLoaderRoute: typeof FinanceCashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/units': {
      id: '/dashboard/units'
      path: '/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof DashboardUnitsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/company': {
      id: '/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AdminCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/transfers/': {
      id: '/tools/transfers/'
      path: '/tools/transfers'
      fullPath: '/tools/transfers/'
      preLoaderRoute: typeof ToolsTransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/maintenances/': {
      id: '/tools/maintenances/'
      path: '/tools/maintenances'
      fullPath: '/tools/maintenances/'
      preLoaderRoute: typeof ToolsMaintenancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$id/': {
      id: '/tools/$id/'
      path: '/tools/$id'
      fullPath: '/tools/$id/'
      preLoaderRoute: typeof ToolsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/work-orders/': {
      id: '/operations/work-orders/'
      path: '/operations/work-orders'
      fullPath: '/operations/work-orders/'
      preLoaderRoute: typeof OperationsWorkOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/quotes/': {
      id: '/operations/quotes/'
      path: '/operations/quotes'
      fullPath: '/operations/quotes/'
      preLoaderRoute: typeof OperationsQuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/inspections/': {
      id: '/operations/inspections/'
      path: '/operations/inspections'
      fullPath: '/operations/inspections/'
      preLoaderRoute: typeof OperationsInspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/transfers/': {
      id: '/inventory/transfers/'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers/'
      preLoaderRoute: typeof InventoryTransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stocks/': {
      id: '/inventory/stocks/'
      path: '/inventory/stocks'
      fullPath: '/inventory/stocks/'
      preLoaderRoute: typeof InventoryStocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products/': {
      id: '/inventory/products/'
      path: '/inventory/products'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof InventoryProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/movements/': {
      id: '/inventory/movements/'
      path: '/inventory/movements'
      fullPath: '/inventory/movements/'
      preLoaderRoute: typeof InventoryMovementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/transactions/': {
      id: '/finance/transactions/'
      path: '/finance/transactions'
      fullPath: '/finance/transactions/'
      preLoaderRoute: typeof FinanceTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/receivables/': {
      id: '/finance/receivables/'
      path: '/finance/receivables'
      fullPath: '/finance/receivables/'
      preLoaderRoute: typeof FinanceReceivablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payables/': {
      id: '/finance/payables/'
      path: '/finance/payables'
      fullPath: '/finance/payables/'
      preLoaderRoute: typeof FinancePayablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/accounts/': {
      id: '/finance/accounts/'
      path: '/finance/accounts'
      fullPath: '/finance/accounts/'
      preLoaderRoute: typeof FinanceAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/vehicles/': {
      id: '/crm/vehicles/'
      path: '/crm/vehicles'
      fullPath: '/crm/vehicles/'
      preLoaderRoute: typeof CrmVehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers/': {
      id: '/crm/customers/'
      path: '/crm/customers'
      fullPath: '/crm/customers/'
      preLoaderRoute: typeof CrmCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$id/edit': {
      id: '/tools/$id/edit'
      path: '/tools/$id/edit'
      fullPath: '/tools/$id/edit'
      preLoaderRoute: typeof ToolsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/quotes/$id': {
      id: '/portal/quotes/$id'
      path: '/portal/quotes/$id'
      fullPath: '/portal/quotes/$id'
      preLoaderRoute: typeof PortalQuotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/work-orders/kanban': {
      id: '/operations/work-orders/kanban'
      path: '/operations/work-orders/kanban'
      fullPath: '/operations/work-orders/kanban'
      preLoaderRoute: typeof OperationsWorkOrdersKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/work-orders/$id': {
      id: '/operations/work-orders/$id'
      path: '/operations/work-orders/$id'
      fullPath: '/operations/work-orders/$id'
      preLoaderRoute: typeof OperationsWorkOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/scheduling/new': {
      id: '/operations/scheduling/new'
      path: '/operations/scheduling/new'
      fullPath: '/operations/scheduling/new'
      preLoaderRoute: typeof OperationsSchedulingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/scheduling/checkin': {
      id: '/operations/scheduling/checkin'
      path: '/operations/scheduling/checkin'
      fullPath: '/operations/scheduling/checkin'
      preLoaderRoute: typeof OperationsSchedulingCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/scheduling/calendar': {
      id: '/operations/scheduling/calendar'
      path: '/operations/scheduling/calendar'
      fullPath: '/operations/scheduling/calendar'
      preLoaderRoute: typeof OperationsSchedulingCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/quotes/new': {
      id: '/operations/quotes/new'
      path: '/operations/quotes/new'
      fullPath: '/operations/quotes/new'
      preLoaderRoute: typeof OperationsQuotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/quotes/$id': {
      id: '/operations/quotes/$id'
      path: '/operations/quotes/$id'
      fullPath: '/operations/quotes/$id'
      preLoaderRoute: typeof OperationsQuotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/inspections/new': {
      id: '/operations/inspections/new'
      path: '/operations/inspections/new'
      fullPath: '/operations/inspections/new'
      preLoaderRoute: typeof OperationsInspectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/inspections/$id': {
      id: '/operations/inspections/$id'
      path: '/operations/inspections/$id'
      fullPath: '/operations/inspections/$id'
      preLoaderRoute: typeof OperationsInspectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products/new': {
      id: '/inventory/products/new'
      path: '/inventory/products/new'
      fullPath: '/inventory/products/new'
      preLoaderRoute: typeof InventoryProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products/$id': {
      id: '/inventory/products/$id'
      path: '/inventory/products/$id'
      fullPath: '/inventory/products/$id'
      preLoaderRoute: typeof InventoryProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/vehicles/new': {
      id: '/crm/vehicles/new'
      path: '/crm/vehicles/new'
      fullPath: '/crm/vehicles/new'
      preLoaderRoute: typeof CrmVehiclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/vehicles/$id': {
      id: '/crm/vehicles/$id'
      path: '/crm/vehicles/$id'
      fullPath: '/crm/vehicles/$id'
      preLoaderRoute: typeof CrmVehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers/new': {
      id: '/crm/customers/new'
      path: '/crm/customers/new'
      fullPath: '/crm/customers/new'
      preLoaderRoute: typeof CrmCustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers/$id': {
      id: '/crm/customers/$id'
      path: '/crm/customers/$id'
      fullPath: '/crm/customers/$id'
      preLoaderRoute: typeof CrmCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/vehicles/$id/history': {
      id: '/portal/vehicles/$id/history'
      path: '/portal/vehicles/$id/history'
      fullPath: '/portal/vehicles/$id/history'
      preLoaderRoute: typeof PortalVehiclesIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/vehicles/$id/history': {
      id: '/operations/vehicles/$id/history'
      path: '/operations/vehicles/$id/history'
      fullPath: '/operations/vehicles/$id/history'
      preLoaderRoute: typeof OperationsVehiclesIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardUnitsRoute: typeof DashboardUnitsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardUnitsRoute: DashboardUnitsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminCompanyRoute: AdminCompanyRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  FinanceCashFlowRoute: FinanceCashFlowRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinanceDreRoute: FinanceDreRoute,
  ToolsNewRoute: ToolsNewRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
  CrmCustomersIdRoute: CrmCustomersIdRoute,
  CrmCustomersNewRoute: CrmCustomersNewRoute,
  CrmVehiclesIdRoute: CrmVehiclesIdRoute,
  CrmVehiclesNewRoute: CrmVehiclesNewRoute,
  InventoryProductsIdRoute: InventoryProductsIdRoute,
  InventoryProductsNewRoute: InventoryProductsNewRoute,
  OperationsInspectionsIdRoute: OperationsInspectionsIdRoute,
  OperationsInspectionsNewRoute: OperationsInspectionsNewRoute,
  OperationsQuotesIdRoute: OperationsQuotesIdRoute,
  OperationsQuotesNewRoute: OperationsQuotesNewRoute,
  OperationsSchedulingCalendarRoute: OperationsSchedulingCalendarRoute,
  OperationsSchedulingCheckinRoute: OperationsSchedulingCheckinRoute,
  OperationsSchedulingNewRoute: OperationsSchedulingNewRoute,
  OperationsWorkOrdersIdRoute: OperationsWorkOrdersIdRoute,
  OperationsWorkOrdersKanbanRoute: OperationsWorkOrdersKanbanRoute,
  PortalQuotesIdRoute: PortalQuotesIdRoute,
  ToolsIdEditRoute: ToolsIdEditRoute,
  CrmCustomersIndexRoute: CrmCustomersIndexRoute,
  CrmVehiclesIndexRoute: CrmVehiclesIndexRoute,
  FinanceAccountsIndexRoute: FinanceAccountsIndexRoute,
  FinancePayablesIndexRoute: FinancePayablesIndexRoute,
  FinanceReceivablesIndexRoute: FinanceReceivablesIndexRoute,
  FinanceTransactionsIndexRoute: FinanceTransactionsIndexRoute,
  InventoryMovementsIndexRoute: InventoryMovementsIndexRoute,
  InventoryProductsIndexRoute: InventoryProductsIndexRoute,
  InventoryStocksIndexRoute: InventoryStocksIndexRoute,
  InventoryTransfersIndexRoute: InventoryTransfersIndexRoute,
  OperationsInspectionsIndexRoute: OperationsInspectionsIndexRoute,
  OperationsQuotesIndexRoute: OperationsQuotesIndexRoute,
  OperationsWorkOrdersIndexRoute: OperationsWorkOrdersIndexRoute,
  ToolsIdIndexRoute: ToolsIdIndexRoute,
  ToolsMaintenancesIndexRoute: ToolsMaintenancesIndexRoute,
  ToolsTransfersIndexRoute: ToolsTransfersIndexRoute,
  OperationsVehiclesIdHistoryRoute: OperationsVehiclesIdHistoryRoute,
  PortalVehiclesIdHistoryRoute: PortalVehiclesIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
